/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndkold_study_com_ndkolddemo_Java2CJNI */

#ifndef _Included_ndkold_study_com_ndkolddemo_Java2CJNI
#define _Included_ndkold_study_com_ndkolddemo_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndkold_study_com_ndkolddemo_Java2CJNI
 * Method:    java2C
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndkold_study_com_ndkolddemo_Java2CJNI_java2C
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
